### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by cmannett85** [cmannett85/malbolge#13]
### Tasks
1. Create a set of descriptive exception types
2. Use Boost.Log to define logging levels, settable from the command line
3. Improve syntax checking error reporting

### Exceptions

- [x] `basic_exception`
Base class, can just be `std::runtime` error.
- [x] `parse_error` -> `basic_exception`
Thrown when a file or piped input fails parsing, also when a file is loaded from disk.  Should contain a line and char counter if the file was successfully loaded.
- [x] `execution_error` -> `basic_exception`
Thrown when program execution fails.  Should report the execution step, might be useful in debugging.
- [x] `system_error` -> `basic_exception`
Thrown when a part of the virtual machine fails.  Carries an error code.

### Log Levels

- [x] Create a generic set of log levels: `ERROR`, `INFO`, `DEBUG`, `VERBOSE_DEBUG`.  These correspond to the `-v` multiplier flags in the command line:
  - `<No flag>` = `ERROR`
  - `-v` = `INFO`
  - `-vv` = `DEBUG`
  - `-vvv` = `VERBOSE_DEBUG`
- [x] Each subsystem will have its own log source
- [x] By default the sink is cerr, this allows VM output to separated using the teminal:
 - `malbolge -vvv ./hello_world.mal 2> ./log_output.txt`

### Syntax Checking Error Reporting
The line and column will be stored during parsing, so if there is any bad instructions, the offending character can easily be found in the input file.
